{% set name = "fixedint" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fixedint-{{ version }}.tar.gz
  sha256: aeea0c7a3a54e5371ed632f9a97719316699f64f863ffce4414ef0f925255d17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - fixedint
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nneonneo/fixedint
  summary: simple fixed-width integers
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
